### ISSUE TITLE
DType API mismatch

### ISSUE THREAD

**Issue by astrojuanlu** [seberg/experimental_user_dtypes#5]
If I change `numpy/core/include/numpy/experimental_dtype_api.h` to have `#define __EXPERIMENTAL_DTYPE_VERSION 3`, then I still get this error:

```
$ NUMPY_EXPERIMENTAL_DTYPE_API=1 python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from experimental_user_dtypes import float64unit as u
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "experimental_user_dtypes/float64unit.pyx", line 22, in init experimental_user_dtypes.float64unit
RuntimeError: Experimental DType API version 3 requested, but NumPy is exporting version 2.  Recompile your DType and/or upgrade NumPy to match.
```

and if I change `experimental_user_dtypes/float64unit.pyx` to request version 2, then I get this error:

```
$ NUMPY_EXPERIMENTAL_DTYPE_API=1 python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from experimental_user_dtypes import float64unit as u
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "experimental_user_dtypes/float64unit.pyx", line 22, in init experimental_user_dtypes.float64unit
RuntimeError: DType API version 2 did not match header version 3. Please update the import statement and check for API changes.
```

Schrödinger's API version? 😛

**Comment by seberg** [comment]
Yes, there was is a Schrödinger here but modifying the header should fix it.  Could you double check that your NumPy is/was up to date (from the `main` branch, the 1.22 release would be stuck on "version 2")?
I also had a problem on my debian sometimes with debian shipping additional headers that get picked up, using `--no-build-isolution` while building this (if you use pip) might help.

**Comment by astrojuanlu** [comment]
Weird, I used `main` now (was using 1.22 before), I installed using `--no-build-isolation`, and I still get the `RuntimeError: DType API version 3 did not match header version 2. Please update the import statement and check for API changes.` error.

The problem can be reproduced with this Dockerfile, maybe I'm missing something?

```
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y --no-install-recommends git python3.8-venv python3.8-dev build-essential

RUN git clone --recursive https://github.com/numpy/numpy.git
RUN sed -i 's;#define __EXPERIMENTAL_DTYPE_VERSION 2;#define __EXPERIMENTAL_DTYPE_VERSION 3;g' numpy/numpy/core/include/numpy/experimental_dtype_api.h

RUN python3.8 -m venv .venv

RUN /.venv/bin/python -m pip install numpy/

RUN git clone https://github.com/seberg/experimental_user_dtypes.git

RUN /.venv/bin/python -m pip install wheel unyt cython
RUN /.venv/bin/python -m pip install experimental_user_dtypes/

RUN cd /tmp && /.venv/bin/python -c "from experimental_user_dtypes import float64unit as u"
```

**Comment by seberg** [comment]
Will check, cloning NumPy is taking forever in that environment.

If you want to beat me to it, maybe try modifying
```
RUN /.venv/bin/python -m pip install experimental_user_dtypes/
```
to read
```
RUN /.venv/bin/python -m pip install experimental_user_dtypes/ --no-build-isolation
```
I am thinking ubuntu may have that problem of finding the `numpy` headers because they are added to the `python` headers (where they don't really quite belong really, I guess) and not only in the place `np.get_include()` says they should be.

**Comment by seberg** [comment]
Need to get better at docker, this seems to work now, although I think there may have been some issues due to caching for a short time?
```
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y --no-install-recommends git python3.8-venv python3.8-dev build-essential

RUN git clone --recursive https://github.com/numpy/numpy.git
RUN sed -i 's;#define __EXPERIMENTAL_DTYPE_VERSION 2;#define __EXPERIMENTAL_DTYPE_VERSION 3;g' numpy/numpy/core/include/numpy/experimental_dtype_api.h

RUN python3.8 -m venv .venv

RUN /.venv/bin/python -m pip install numpy/

RUN git clone https://github.com/seberg/experimental_user_dtypes.git

RUN /.venv/bin/python -m pip install wheel unyt cython
RUN /.venv/bin/python -m pip install experimental_user_dtypes/ --no-build-isolation

ENV NUMPY_EXPERIMENTAL_DTYPE_API=1
RUN cd /tmp && /.venv/bin/python -c "from experimental_user_dtypes import float64unit as u"
```

**Comment by astrojuanlu** [comment]
I confirm that the Dockerfile works (obviously) and that it works on my machine too! As you say, maybe there was some weird caching going on.

> I am thinking ubuntu may have that problem of finding the numpy headers because they are added to the python headers 

Wow, this is shocking. If you have any pointers I'll be happy to dig more, otherwise I'll focus on the task at hand 😄

**Comment by astrojuanlu** [comment]
Unfortunately, I did some quick benchmarks and the results are unfortunately not very impressive:

```
In [62]: from astropy import units as u_astro

In [63]: import unyt as u_unyt

In [64]: q_astro = np.random.randn(1000) << u_astro.imperial.Fahrenheit

In [65]: eq_astro = u_astro.temperature()

In [67]: q_unyt = np.random.randn(1000) * u_unyt.Fahrenheit

In [68]: # q_np_exp = ...  # This was a bit involved, because building the array from a list of values messed up the dtype

In [69]: %timeit q_astro.to(u_astro.Celsius, equivalencies=eq_astro)
27.2 µs ± 839 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [70]: %timeit q_unyt.to(u_unyt.Celsius)
20.8 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [71]: %timeit q_np_exp.astype(u_np_exp.Float64UnitDType("Celsius"))
143 µs ± 21.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [72]: c_np_exp = u_np_exp.Float64UnitDType("Celsius")

In [73]: %timeit c_np_exp = u_np_exp.Float64UnitDType("Celsius")  # It turns out that this is slow, we cache it
85.8 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [74]: %timeit q_np_exp.astype(c_np_exp)  # But still...
27.4 µs ± 8.26 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

So, `experimental_user_dtypes.float64unit` is as slow as Astropy at this point, and within the same order of magnitude as unyt.

However, I reckon that perhaps there's a large overhead in calling unyt from Cython, and that a unit system implemented in Cython or C would be super fast? There's only one way to find out I guess :)

Feel free to close this issue, happy to continue the conversation either way! Thanks a lot for the help

**Comment by seberg** [comment]
Ok, good that it works, though.  I never expected this to be particularly fast, there are two things:
* All unit handling is done fully in Python
* The "math" is written in Cython, which is not terrible (almost as good as C), but NumPy is much better since it leverages SIMD.  So reusing the existing loops would modify this.

Of course it may also be that unit dealing just costs times and your speed observations have nothing to do with overheads.

**Comment by seberg** [comment]
For what its worth, 10µs is indeed mostly in the overhead of unyt conversion... 1000 elements is just very small.  But with some caching and a [new implementation](https://github.com/seberg/unitdtype):

```
In [1]: import numpy as np; import unitdtype as udt; import unyt

In [2]: q_unyt = np.random.randn(1000) * unyt.Fahrenheit

In [3]: %timeit q_unyt.to(unyt.Celsius)
16.5 µs ± 35.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: q_dt = np.random.randn(1000).view(udt.Float64Unit("Fahrenheit"))

In [5]: %timeit q_dt.astype(udt.Float64Unit("Celsius"))
3.18 µs ± 32.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [6]: q_unyt = np.random.randn(1000000) * unyt.Fahrenheit

In [7]: %timeit q_unyt.to(unyt.Celsius)
299 µs ± 392 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [8]: q_dt = np.random.randn(1000000).view(udt.Float64Unit("Fahrenheit"))

In [9]: %timeit q_dt.astype(udt.Float64Unit("Celsius"))
173 µs ± 6.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
(Note that the speed advantage for big arrays is relevant for temperatures due to the `offset`, meaning that conversion is two operations in Python wrappers.)

**Comment by astrojuanlu** [comment]
That's promising! I had some installation problems though (first related to [a bug in GCC 9](https://stackoverflow.com/q/64493692/554319) and then something else) but I understand that the code is in flux, so I can either hold off the error reports until the dust has settled or send them your way, whatever is more helpful.

**Comment by seberg** [comment]
I am fine with bug report. GCC bug seems annoying :/.  If you were unlucky, I did change some dereferencing, although the update to the NumPy branch and the one to the project should have been only ten minutes apart :).

So bug reports welcome, since the pushed changes are compiling and running fine here.
